## Final Project Submission

Please fill out:
* Student name: Dalton Rabb
* Student pace: full time
* Scheduled project review date/time: 3/26
* Instructor name: James Irving
* Blog post URL:

## Microsoft Studios Pitch Analysis

In [78]:
# Your code here - remember to use markdown cells for comments as well!

In [79]:
import pandas as pd
import numpy as np

In [80]:
basics = pd.read_csv('zippeddata/imdb.title.basics.csv.gz')
ratings = pd.read_csv('zippeddata/imdb.title.ratings.csv.gz')
gross = pd.read_csv('zippeddata/bom.movie_gross.csv.gz')
popularity = pd.read_csv('zippeddata/tmdb.movies.csv.gz')
budgets = pd.read_csv('zippeddata/tn.movie_budgets.csv.gz')

In [81]:
basics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146144 entries, 0 to 146143
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   tconst           146144 non-null  object
 1   primary_title    146144 non-null  object
 2   original_title   146123 non-null  object
 3   start_year       146144 non-null  int64
 4   runtime_minutes  114405 non-null  float64
 5   genres           140736 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 6.7+ MB

In [82]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73856 entries, 0 to 73855
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   tconst         73856 non-null  object
 1   averagerating  73856 non-null  float64
 2   numvotes       73856 non-null  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.7+ MB

In [83]:
gross.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3387 entries, 0 to 3386
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           3387 non-null   object
 1   studio          3382 non-null   object
 2   domestic_gross  3359 non-null   float64
 3   foreign_gross   2037 non-null   object
 4   year            3387 non-null   int64
dtypes: float64(1), int64(1), object(3)
memory usage: 132.4+ KB

In [84]:
basics.describe()

          start_year  runtime_minutes
count  146144.000000    114405.000000
mean     2014.621798        86.187247
std         2.733583       166.360590
min      2010.000000         1.000000
25%      2012.000000        70.000000
50%      2015.000000        87.000000
75%      2017.000000        99.000000
max      2115.000000     51420.000000

In [85]:
basics['genres'].value_counts()[:10]

Documentary              32185
Drama                    21486
Comedy                    9177
Horror                    4372
Comedy,Drama              3519
Thriller                  3046
Action                    2219
Biography,Documentary     2115
Drama,Romance             2079
Comedy,Drama,Romance      1558
Name: genres, dtype: int64

In [86]:
popularity.describe()

        Unnamed: 0             id    popularity  vote_average    vote_count
count  26517.00000   26517.000000  26517.000000  26517.000000  26517.000000
mean   13258.00000  295050.153260      3.130912      5.991281    194.224837
std     7654.94288  153661.615648      4.355229      1.852946    960.961095
min        0.00000      27.000000      0.600000      0.000000      1.000000
25%     6629.00000  157851.000000      0.600000      5.000000      2.000000
50%    13258.00000  309581.000000      1.374000      6.000000      5.000000
75%    19887.00000  419542.000000      3.694000      7.000000     28.000000
max    26516.00000  608444.000000     80.773000     10.000000  22186.000000

In [87]:
budgets.head()

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
0,1,"Dec 18, 2009",Avatar,"$425,000,000","$760,507,625","$2,776,345,279"
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,"$410,600,000","$241,063,875","$1,045,663,875"
2,3,"Jun 7, 2019",Dark Phoenix,"$350,000,000","$42,762,350","$149,762,350"
3,4,"May 1, 2015",Avengers: Age of Ultron,"$330,600,000","$459,005,868","$1,403,013,963"
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,"$317,000,000","$620,181,382","$1,316,721,747"

In [88]:
budgets['worldwide_gross'] = budgets['worldwide_gross'].str.replace(',', '')
budgets['worldwide_gross'] = budgets['worldwide_gross'].str.replace('$', '')
budgets['production_budget'] = budgets['production_budget'].str.replace(',', '')
budgets['production_budget'] = budgets['production_budget'].str.replace('$', '')

In [89]:
print(budgets['worldwide_gross'])

0       2776345279
1       1045663875
2        149762350
3       1403013963
4       1316721747
           ...
5777             0
5778        240495
5779          1338
5780             0
5781        181041
Name: worldwide_gross, Length: 5782, dtype: object

In [90]:
wwg_list = budgets['worldwide_gross'].tolist()
wwg_list = list(map(int, wwg_list))

In [91]:
wwg_list

[2776345279,
 1045663875,
 149762350,
 1403013963,
 1316721747,
 2053311220,
 2048134200,
 963420425,
 655945209,
 879620923,
 1084439099,
 393151347,
 260002115,
 282778100,
 586477240,
 894860230,
 1140069413,
 867500281,
 1017003568,
 935213767,
 960366855,
 945577621,
 1234846267,
 374085065,
 788241137,
 591692078,
 1517935897,
 1066215812,
 667999518,
 417341288,
 757890267,
 313477717,
 602893340,
 1648854864,
 654213485,
 836519699,
 1104039076,
 459260946,
 322459006,
 550517357,
 367262558,
 1348258224,
 2208208395,
 1242520711,
 1049102856,
 1021215193,
 1068879522,
 1215392272,
 862316233,
 795110670,
 1025491110,
 1110526981,
 743588329,
 490359051,
 747862775,
 708996336,
 560155383,
 400062763,
 757677748,
 652220086,
 365491792,
 219535492,
 336359676,
 1123790543,
 409953905,
 197687603,
 1518722794,
 467381584,
 531514650,
 351040419,
 315709697,
 411002906,
 333771037,
 585171547,
 1001996207,
 786635413,
 554606532,
 561072059,
 335802233,
 259357408,
 619234314,
 846980024,
 720539572,
 758536735,
 802402853,
 532508025,
 256585882,
 348902025,
 180047784,
 215098356,
 181982519,
 787456552,
 542537546,
 529530715,
 370541256,
 1123061550,
 962854547,
 854235992,
 880166350,
 746059887,
 731463377,
 798008101,
 524283695,
 381687380,
 383541369,
 302469017,
 221229335,
 405760225,
 174131329,
 264246220,
 139630336,
 151716815,
 1305772799,
 770867516,
 621156389,
 714401889,
 710644566,
 311365187,
 401021746,
 433058296,
 300150546,
 345004422,
 206627518,
 402976036,
 299276941,
 276928112,
 756244673,
 676404566,
 652127828,
 494870992,
 496511521,
 666379375,
 384169424,
 176038324,
 1259199706,
 1146894640,
 807330936,
 835524642,
 648986787,
 789300444,
 529076069,
 355408305,
 329631958,
 217986320,
 181674817,
 425522281,
 122603824,
 418186950,
 432150894,
 290930148,
 167297191,
 489592267,
 449239855,
 708272592,
 821133378,
 1272469910,
 1019429616,
 943076457,
 897099794,
 738576929,
 585532684,
 637517365,
 624234272,
 475825484,
 626549695,
 644602516,
 359142722,
 688858992,
 499837368,
 449326618,
 599680774,
 374825760,
 402231063,
 664837547,
 370098020,
 411258433,
 427300260,
 579290136,
 310043823,
 397501348,
 490875846,
 484161265,
 319713881,
 287594577,
 292817841,
 328015029,
 305270083,
 195080579,
 238202668,
 205440387,
 142634358,
 334486852,
 151525973,
 39549758,
 0,
 179357126,
 746921271,
 694713230,
 614586270,
 448191819,
 269806430,
 306900902,
 121671925,
 229008658,
 431942139,
 634954103,
 386839614,
 554600000,
 441767803,
 370569776,
 517599142,
 285400000,
 375740705,
 456810575,
 203018919,
 268314513,
 199646680,
 138836756,
 821706375,
 186976250,
 76416746,
 265573859,
 245075434,
 85131830,
 829724737,
 573068425,
 532938302,
 361730660,
 245724600,
 212912137,
 286896578,
 245328374,
 157956466,
 163818556,
 170293899,
 606836535,
 366942531,
 864868047,
 796907323,
 444043396,
 623144660,
 631910531,
 518858449,
 385997896,
 341528518,
 554987477,
 321887208,
 273271982,
 492846291,
 290650494,
 352831065,
 373993951,
 251499665,
 215080810,
 79076678,
 519258283,
 689420051,
 356148063,
 615461394,
 353756621,
 1341693157,
 766575131,
 975047606,
 960431568,
 767820459,
 406875536,
 630163454,
 485004754,
 535663443,
 556319450,
 510878762,
 493214888,
 344150134,
 376000000,
 402448265,
 280355920,
 238317814,
 304115534,
 211856088,
 240759682,
 61642798,
 61698899,
 345141403,
 549588516,
 328711434,
 416168316,
 289480691,
 620912003,
 229545589,
 428056280,
 227200000,
 286192091,
 287916633,
 142531552,
 166000000,
 242981799,
 107212751,
 167849187,
 93394462,
 163018913,
 49628177,
 258751370,
 853628605,
 1027044677,
 848998877,
 656695615,
 559757719,
 416456852,
 178200000,
 165149302,
 77628265,
 132999811,
 232017848,
 289847930,
 786680557,
 693698673,
 579446407,
 486124090,
 456258539,
 563749323,
 382288147,
 295075882,
 362989076,
 339504276,
 215300000,
 330780051,
 208370892,
 302239672,
 229155503,
 295986876,
 263880341,
 177241171,
 348547523,
 172022517,
 152364370,
 127983283,
 76482461,
 150468000,
 218853353,
 167910690,
 72004159,
 3100000,
 887210985,
 133818283,
 87683966,
 655271443,
 119266661,
 348629585,
 298815224,
 270997378,
 269065678,
 402156682,
 10364769,
 408803696,
 232643008,
 457683805,
 362000072,
 133401882,
 212282709,
 594420283,
 358824714,
 465195589,
 130673154,
 879225135,
 515419827,
 336529144,
 362211740,
 331323410,
 449948323,
 310650574,
 365300000,
 267985456,
 236827677,
 170936470,
 212956024,
 389870414,
 262794441,
 234400000,
 325500000,
 169296573,
 311979256,
 99123656,
 249488115,
 243388614,
 278731369,
 212026975,
 96221971,
 145395745,
 171377916,
 139716717,
 121100000,
 69548641,
 95255485,
 115149422,
 82145379,
 209461378,
 91800000,
 97523020,
 220796009,
 126704591,
 89693309,
 103039258,
 59918422,
 85287417,
 7094995,
 98227017,
 250091610,
 190325698,
 84747441,
 435040395,
 183124621,
 238521247,
 534551353,
 879765137,
 159691085,
 294680778,
 223050874,
 104907746,
 165720921,
 263898761,
 65700000,
 94894448,
 91669648,
 108874967,
 936429370,
 1141403341,
 934699645,
 273330185,
 404561724,
 365900000,
 470986200,
 162839667,
 614726752,
 304249198,
 23911362,
 18517322,
 187861183,
 964496193,
 587790539,
 511358276,
 347425832,
 498438212,
 859701857,
 375381768,
 288693989,
 487519809,
 289660619,
 259736090,
 303500000,
 191145256,
 239373970,
 165900000,
 202910991,
 366101666,
 162525156,
 249517956,
 186049020,
 203932174,
 244041804,
 235900000,
 155750628,
 191200000,
 162753837,
 200859554,
 157092943,
 328325007,
 143049560,
 169400000,
 106000000,
 273477501,
 87420776,
 203877963,
 120100000,
 140900000,
 65716126,
 63356133,
 139877913,
 10551417,
 20466016,
 0,
 0,
 495700000,
 105021488,
 159487563,
 333132750,
 350100280,
 148715342,
 427230516,
 385000317,
 450728529,
 311001124,
 315268353,
 363064265,
 299477886,
 276014965,
 378505812,
 362899733,
 340384141,
 208542162,
 185708462,
 311744465,
 224614744,
 250649836,
 191932158,
 150422946,
 66941559,
 173613482,
 205190324,
 157794205,
 161510853,
 96971293,
 137298489,
 80831893,
 149717124,
 345033359,
 44650003,
 113026383,
 78353508,
 78948765,
 113487912,
 83080084,
 48056764,
 74132631,
 35681080,
 386665550,
 276294164,
 166307945,
 141507355,
 237685089,
 143985708,
 222640812,
 160388063,
 191558505,
 268268174,
 96024898,
 0,
 484468608,
 677923379,
 586464305,
 457697994,
 310660018,
 469500298,
 266824291,
 416385488,
 343397247,
 245800000,
 349464664,
 247023808,
 349088523,
 226739416,
 260700012,
 299461782,
 266685242,
 168311558,
 241200000,
 221468935,
 183354514,
 214974953,
 182782518,
 180585259,
 224117573,
 204774690,
 165173909,
 158750817,
 177993801,
 180188905,
 250200000,
 210315681,
 213691277,
 158926474,
 170805525,
 237370350,
 142783718,
 164800000,
 106515310,
 147080413,
 69618634,
 136047317,
 96148711,
 181038616,
 113351496,
 131159306,
 98983590,
 71485043,
 50632037,
 141475336,
 58270391,
 119668350,
 98341932,
 105299638,
 101371017,
 99010667,
 123368842,
 66554547,
 158908290,
 130818912,
 108469033,
 29725663,
 54540662,
 53508858,
 26703184,
 86787530,
 69131860,
 20841123,
 33463969,
 113325743,
 40147042,
 6300451,
 986214868,
 318146162,
 150519217,
 317668058,
 274392649,
 206455420,
 108086731,
 179265204,
 43957541,
 60680125,
 102028919,
 1521672,
 190453132,
 975216835,
 236410607,
 69845011,
 35129610,
 886750534,
 817400878,
 511002426,
 634454789,
 1034727750,
 618638999,
 651899282,
 556559566,
 272223430,
 371917043,
 296872367,
 342416460,
 336069511,
 196320329,
 203035572,
 342769200,
 155708695,
 197504758,
 97387965,
 211562435,
 218673959,
 221594911,
 141267370,
 213500000,
 119512771,
 73521587,
 94944017,
 131492772,
 95572749,
 104949584,
 85632458,
 72785169,
 54344321,
 71523271,
 39251128,
 127361412,
 89758389,
 77636443,
 219519367,
 50409753,
 36751979,
 34009180,
 14623082,
 30626690,
 5409517,
 0,
 0,
 1160336173,
 311013181,
 248099143,
 162870525,
 352327887,
 103891409,
 50168294,
 527071022,
 109362966,
 71880305,
 86509602,
 176101721,
 209045244,
 96947540,
 54616869,
 37306334,
 62176754,
 257641634,
 294156605,
 408269295,
 937008132,
 461651246,
 443483213,
 351500000,
 310138178,
 267200000,
 297115976,
 308700000,
 316915264,
 300854823,
 239814025,
 207154748,
 175807183,
 207068340,
 202726605,
 250700000,
 172878928,
 213463976,
 172543519,
 156815529,
 114658262,
 158702748,
 183353431,
 117800000,
 123954323,
 131011757,
 160379930,
 122737201,
 220241723,
 94973540,
 54243125,
 137431619,
 70546865,
 88933562,
 116625798,
 137022245,
 61031932,
 131445884,
 49730854,
 69792704,
 60279822,
 69157016,
 58757178,
 49252761,
 103735965,
 65409046,
 19870567,
 33076815,
 25852508,
 58953319,
 73591500,
 14294842,
 13596911,
 20107933,
 19665004,
 35417162,
 38992292,
 543464573,
 86796502,
 145951861,
 706102828,
 193500000,
 217214143,
 113542091,
 87173475,
 77224232,
 75685268,
 33462011,
 60265197,
 54462971,
 350976753,
 118556530,
 137489730,
 18115927,
 25357771,
 211700000,
 189176423,
 194169619,
 485035085,
 374105123,
 273346281,
 386116343,
 335802271,
 463517383,
 527079962,
 442169052,
 172825854,
 261400000,
 250800000,
 163527824,
 232585748,
 211739043,
 128468793,
 262758310,
 233700000,
 128874043,
 139829625,
 255000000,
 137768975,
 148345997,
 163295654,
 69688384,
 141205169,
 180148897,
 104267443,
 156974557,
 168065700,
 131353165,
 48164150,
 43545364,
 221297061,
 240647629,
 39017984,
 100851705,
 72516819,
 33447612,
 62761005,
 58545540,
 38253433,
 56824633,
 41636243,
 74575290,
 17218916,
 40650842,
 21774432,
 10014234,
 26670920,
 122519874,
 516279,
 101636047,
 63200000,
 133603463,
 1038812584,
 296338663,
 188657593,
 68310140,
 25052000,
 207500000,
 127630030,
 107822813,
 147864886,
 40159017,
 18708848,
 368567189,
 145594548,
 310566162,
 132493015,
 265878536,
 81149689,
 554516671,
 516567575,
 457729388,
 454161935,
 253555383,
 247812011,
 290701374,
 264118201,
 238524556,
 214357371,
 172450423,
 356429941,
 176262839,
 164285587,
 149705852,
 218613188,
 217670152,
 200700000,
 199043309,
 152457863,
 165890634,
 196439693,
 170200225,
 157670733,
 135015330,
 206598789,
 217370736,
 130968579,
 124715863,
 137551594,
 100230832,
 186883563,
 126037057,
 102332848,
 165048228,
 252091016,
 90723216,
 162778384,
 195194085,
 71719931,
 87123569,
 129832389,
 99823958,
 159946489,
 175863783,
 56709981,
 101134059,
 108119662,
 159356941,
 98819789,
 100645801,
 90482317,
 111946251,
 113461527,
 104429625,
 131377412,
 104324083,
 101382396,
 70883171,
 160700000,
 95538560,
 68336997,
 104100903,
 197578586,
 105203825,
 57604723,
 82812456,
 67312826,
 82150183,
 108996113,
 81079566,
 78481410,
 124514011,
 88832210,
 36850101,
 78080697,
 47818913,
 121327628,
 33956608,
 32983332,
 47371191,
 62599159,
 54994757,
 38522450,
 75965567,
 39235486,
 30063805,
 84154026,
 147985373,
 71073932,
 26673242,
 80767884,
 49473093,
 48585416,
 49238525,
 35319689,
 39006188,
 20541668,
 66655938,
 14816494,
 14816379,
 29575033,
 12069719,
 50648806,
 10597070,
 24148488,
 30396134,
 13233220,
 11427090,
 194058503,
 0,
 0,
 87527651,
 28348446,
 801025593,
 547326372,
 158905324,
 188715611,
 87100000,
 50365498,
 100687083,
 93672764,
 59431365,
 41348628,
 100929666,
 80480566,
 31627370,
 415247258,
 295874190,
 58085235,
 153007424,
 149217355,
 104364680,
 38329114,
 62097495,
 213116401,
 195660942,
 198006880,
 47313824,
 359495591,
 679850637,
 362605033,
 894985342,
 366784257,
 330425040,
 307311093,
 347100000,
 300200000,
 273814019,
 381398492,
 220648184,
 174463257,
 126425115,
 345922730,
 192903624,
 371350619,
 282300000,
 152269033,
 163838217,
 ...]

In [92]:
pb_list = budgets['production_budget'].tolist()
pb_list = list(map(int, pb_list))

In [93]:
pb_list

[425000000,
 410600000,
 350000000,
 330600000,
 317000000,
 306000000,
 300000000,
 300000000,
 300000000,
 300000000,
 275000000,
 275000000,
 275000000,
 275000000,
 260000000,
 258000000,
 250000000,
 250000000,
 250000000,
 250000000,
 250000000,
 250000000,
 250000000,
 232000000,
 230000000,
 230000000,
 225000000,
 225000000,
 225000000,
 225000000,
 220000000,
 220000000,
 217000000,
 215000000,
 215000000,
 210000000,
 210000000,
 210000000,
 210000000,
 207000000,
 205000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 200000000,
 195000000,
 195000000,
 195000000,
 190000000,
 190000000,
 190000000,
 190000000,
 190000000,
 190000000,
 187500000,
 186000000,
 185000000,
 185000000,
 185000000,
 185000000,
 185000000,
 185000000,
 182000000,
 180000000,
 180000000,
 180000000,
 180000000,
 180000000,
 180000000,
 180000000,
 180000000,
 180000000,
 179000000,
 178000000,
 178000000,
 178000000,
 178000000,
 175000000,
 175000000,
 175000000,
 175000000,
 175000000,
 175000000,
 175000000,
 175000000,
 175000000,
 175000000,
 175000000,
 175000000,
 175000000,
 175000000,
 175000000,
 175000000,
 175000000,
 170000000,
 170000000,
 170000000,
 170000000,
 170000000,
 170000000,
 170000000,
 170000000,
 170000000,
 170000000,
 170000000,
 170000000,
 170000000,
 170000000,
 165000000,
 165000000,
 165000000,
 165000000,
 165000000,
 165000000,
 165000000,
 163000000,
 160000000,
 160000000,
 160000000,
 160000000,
 160000000,
 160000000,
 160000000,
 160000000,
 160000000,
 160000000,
 160000000,
 160000000,
 156000000,
 155000000,
 155000000,
 155000000,
 155000000,
 152000000,
 151500000,
 151000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 150000000,
 149000000,
 145000000,
 145000000,
 145000000,
 145000000,
 145000000,
 145000000,
 145000000,
 144000000,
 142000000,
 140000000,
 140000000,
 140000000,
 140000000,
 140000000,
 140000000,
 140000000,
 140000000,
 140000000,
 140000000,
 140000000,
 140000000,
 140000000,
 139000000,
 138000000,
 138000000,
 137500000,
 137000000,
 137000000,
 136200000,
 135000000,
 135000000,
 135000000,
 135000000,
 135000000,
 135000000,
 135000000,
 135000000,
 135000000,
 132900000,
 132000000,
 132000000,
 130000000,
 130000000,
 130000000,
 130000000,
 130000000,
 130000000,
 130000000,
 130000000,
 130000000,
 130000000,
 130000000,
 130000000,
 130000000,
 130000000,
 130000000,
 130000000,
 130000000,
 130000000,
 129000000,
 127500000,
 127500000,
 127000000,
 127000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 125000000,
 123000000,
 120000000,
 120000000,
 120000000,
 120000000,
 120000000,
 120000000,
 120000000,
 120000000,
 120000000,
 120000000,
 120000000,
 120000000,
 120000000,
 120000000,
 120000000,
 120000000,
 120000000,
 120000000,
 117000000,
 116000000,
 115000000,
 115000000,
 115000000,
 115000000,
 115000000,
 115000000,
 115000000,
 115000000,
 113500000,
 112000000,
 111000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 110000000,
 109000000,
 109000000,
 109000000,
 108000000,
 106000000,
 105000000,
 105000000,
 105000000,
 105000000,
 105000000,
 105000000,
 104000000,
 103300000,
 103000000,
 103000000,
 103000000,
 102500000,
 102000000,
 102000000,
 102000000,
 102000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 100000000,
 99000000,
 99000000,
 99000000,
 98000000,
 97000000,
 97000000,
 95000000,
 95000000,
 95000000,
 95000000,
 95000000,
 95000000,
 95000000,
 95000000,
 95000000,
 95000000,
 95000000,
 95000000,
 94000000,
 94000000,
 94000000,
 94000000,
 94000000,
 93000000,
 93000000,
 92500000,
 92000000,
 92000000,
 92000000,
 92000000,
 91000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 90000000,
 88000000,
 88000000,
 88000000,
 87500000,
 87000000,
 86000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 85000000,
 84000000,
 84000000,
 84000000,
 84000000,
 82500000,
 82500000,
 82500000,
 82500000,
 82000000,
 82000000,
 82000000,
 82000000,
 81000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 80000000,
 79300000,
 79000000,
 79000000,
 78000000,
 78000000,
 78000000,
 78000000,
 78000000,
 78000000,
 77600000,
 77500000,
 77500000,
 77000000,
 76000000,
 76000000,
 76000000,
 76000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 75000000,
 74000000,
 74000000,
 73243106,
 73000000,
 73000000,
 73000000,
 73000000,
 72500000,
 72500000,
 72500000,
 72500000,
 72000000,
 72000000,
 72000000,
 72000000,
 72000000,
 72000000,
 71682975,
 71500000,
 70702619,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 70000000,
 69000000,
 69000000,
 69000000,
 68000000,
 68000000,
 68000000,
 68000000,
 68000000,
 68000000,
 68000000,
 68000000,
 68000000,
 68000000,
 67500000,
 67500000,
 67500000,
 67000000,
 67000000,
 66000000,
 66000000,
 66000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 65000000,
 64000000,
 64000000,
 63700000,
 63000000,
 63000000,
 63000000,
 63000000,
 63000000,
 62000000,
 62000000,
 62000000,
 62000000,
 62000000,
 62000000,
 61000000,
 61000000,
 61000000,
 61000000,
 61000000,
 61000000,
 60720000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 60000000,
 59500000,
 59000000,
 59000000,
 58000000,
 58000000,
 58000000,
 58000000,
 58000000,
 58000000,
 58000000,
 58000000,
 58000000,
 58000000,
 58000000,
 58000000,
 58000000,
 57500000,
 57500000,
 57500000,
 57000000,
 57000000,
 57000000,
 57000000,
 57000000,
 56200000,
 56000000,
 56000000,
 56000000,
 56000000,
 55000000,
 55000000,
 55000000,
 55000000,
 55000000,
 55000000,
 55000000,
 55000000,
 55000000,
 55000000,
 55000000,
 55000000,
 55000000,
 55000000,
 55000000,
 55000000,
 55000000,
 55000000,
 55000000,
 ...]

In [94]:
wwg_array = np.array(wwg_list)
pb_array = np.array(pb_list)

In [95]:
roi_array = wwg_array / pb_array

In [96]:
roi_array = roi_array * 100

In [111]:
roi_list = roi_array.round(2).tolist()
roi_list

[653.26,
 254.67,
 42.79,
 424.38,
 415.37,
 671.02,
 682.71,
 321.14,
 218.65,
 293.21,
 394.34,
 142.96,
 94.55,
 102.83,
 225.57,
 346.85,
 456.03,
 347.0,
 406.8,
 374.09,
 384.15,
 378.23,
 493.94,
 161.24,
 342.71,
 257.26,
 674.64,
 473.87,
 296.89,
 185.49,
 344.5,
 142.49,
 277.83,
 766.91,
 304.29,
 398.34,
 525.73,
 218.7,
 153.55,
 265.95,
 179.15,
 674.13,
 1104.1,
 621.26,
 524.55,
 510.61,
 534.44,
 607.7,
 431.16,
 397.56,
 512.75,
 555.26,
 371.79,
 245.18,
 373.93,
 354.5,
 280.08,
 200.03,
 378.84,
 326.11,
 182.75,
 109.77,
 168.18,
 576.3,
 210.23,
 101.38,
 799.33,
 245.99,
 279.74,
 184.76,
 166.16,
 216.32,
 178.01,
 314.61,
 541.62,
 425.21,
 299.79,
 303.28,
 181.51,
 140.19,
 340.24,
 470.54,
 400.3,
 421.41,
 445.78,
 295.84,
 142.55,
 193.83,
 100.03,
 119.5,
 101.67,
 442.39,
 304.8,
 297.49,
 208.17,
 641.75,
 550.2,
 488.13,
 502.95,
 426.32,
 417.98,
 456.0,
 299.59,
 218.11,
 219.17,
 172.84,
 126.42,
 231.86,
 99.5,
 151.0,
 79.79,
 86.7,
 768.1,
 453.45,
 365.39,
 420.24,
 418.03,
 183.16,
 235.9,
 254.74,
 176.56,
 202.94,
 121.55,
 237.04,
 176.05,
 162.9,
 458.33,
 409.94,
 395.23,
 299.92,
 300.92,
 403.87,
 232.83,
 108.0,
 787.0,
 716.81,
 504.58,
 522.2,
 405.62,
 493.31,
 330.67,
 222.13,
 206.02,
 136.24,
 113.55,
 265.95,
 78.59,
 269.8,
 278.81,
 187.7,
 107.93,
 322.1,
 296.53,
 469.05,
 547.42,
 848.31,
 679.62,
 628.72,
 598.07,
 492.38,
 390.36,
 425.01,
 416.16,
 317.22,
 417.7,
 429.74,
 239.43,
 459.24,
 333.22,
 299.55,
 399.79,
 249.88,
 268.15,
 443.23,
 246.73,
 274.17,
 284.87,
 386.19,
 206.7,
 265.0,
 327.25,
 322.77,
 213.14,
 191.73,
 195.21,
 218.68,
 203.51,
 130.05,
 158.8,
 136.96,
 95.09,
 222.99,
 101.02,
 26.37,
 0.0,
 120.37,
 515.12,
 479.11,
 423.85,
 309.1,
 186.07,
 211.66,
 83.91,
 159.03,
 304.18,
 453.54,
 276.31,
 396.14,
 315.55,
 264.69,
 369.71,
 203.86,
 268.39,
 326.29,
 145.01,
 191.65,
 142.6,
 99.17,
 591.16,
 135.49,
 55.37,
 193.14,
 178.89,
 62.14,
 609.2,
 424.5,
 394.77,
 267.95,
 182.02,
 157.71,
 212.52,
 181.72,
 117.0,
 121.35,
 128.14,
 459.72,
 277.99,
 665.28,
 613.01,
 341.57,
 479.34,
 486.09,
 399.12,
 296.92,
 262.71,
 426.91,
 247.61,
 210.21,
 379.11,
 223.58,
 271.41,
 287.69,
 193.46,
 165.45,
 60.83,
 402.53,
 540.72,
 279.33,
 484.62,
 278.55,
 1073.35,
 613.26,
 780.04,
 768.35,
 614.26,
 325.5,
 504.13,
 388.0,
 428.53,
 445.06,
 408.7,
 394.57,
 275.32,
 300.8,
 321.96,
 224.28,
 190.65,
 243.29,
 169.48,
 192.61,
 49.31,
 49.36,
 280.6,
 457.99,
 273.93,
 346.81,
 241.23,
 517.43,
 191.29,
 356.71,
 189.33,
 238.49,
 239.93,
 118.78,
 138.33,
 202.48,
 89.34,
 139.87,
 77.83,
 135.85,
 41.36,
 221.16,
 735.89,
 893.08,
 738.26,
 571.04,
 486.75,
 362.14,
 154.96,
 143.61,
 67.5,
 117.18,
 207.16,
 261.12,
 715.16,
 630.64,
 526.77,
 441.93,
 414.78,
 512.5,
 347.53,
 268.25,
 329.99,
 308.64,
 195.73,
 300.71,
 189.43,
 274.76,
 208.32,
 269.08,
 239.89,
 161.13,
 316.86,
 156.38,
 138.51,
 116.35,
 69.53,
 136.79,
 198.96,
 152.65,
 65.46,
 2.82,
 813.96,
 122.77,
 80.44,
 606.73,
 112.52,
 332.03,
 284.59,
 258.09,
 256.25,
 383.01,
 9.87,
 393.08,
 225.21,
 444.35,
 351.46,
 129.52,
 207.11,
 582.76,
 351.79,
 456.07,
 128.11,
 879.23,
 515.42,
 336.53,
 362.21,
 331.32,
 449.95,
 310.65,
 365.3,
 267.99,
 236.83,
 170.94,
 212.96,
 389.87,
 262.79,
 234.4,
 325.5,
 169.3,
 311.98,
 99.12,
 249.49,
 243.39,
 278.73,
 212.03,
 96.22,
 145.4,
 171.38,
 139.72,
 121.1,
 69.55,
 95.26,
 115.15,
 82.15,
 209.46,
 91.8,
 97.52,
 220.8,
 126.7,
 89.69,
 103.04,
 59.92,
 85.29,
 7.09,
 98.23,
 252.62,
 192.25,
 85.6,
 443.92,
 188.79,
 245.9,
 562.69,
 926.07,
 168.1,
 310.19,
 234.79,
 110.43,
 174.44,
 277.79,
 69.16,
 99.89,
 96.49,
 114.61,
 996.2,
 1214.26,
 994.36,
 290.78,
 430.38,
 393.44,
 506.44,
 176.04,
 668.18,
 330.71,
 25.99,
 20.13,
 206.44,
 1071.66,
 653.1,
 568.18,
 386.03,
 553.82,
 955.22,
 417.09,
 320.77,
 541.69,
 321.85,
 288.6,
 337.22,
 212.38,
 265.97,
 184.33,
 225.46,
 406.78,
 180.58,
 277.24,
 206.72,
 226.59,
 271.16,
 262.11,
 173.06,
 212.44,
 180.84,
 223.18,
 174.55,
 364.81,
 158.94,
 188.22,
 117.78,
 303.86,
 97.13,
 226.53,
 133.44,
 156.56,
 73.02,
 70.4,
 155.42,
 11.72,
 22.74,
 0.0,
 0.0,
 563.3,
 119.34,
 181.24,
 380.72,
 402.41,
 172.92,
 502.62,
 452.94,
 530.27,
 365.88,
 370.9,
 427.13,
 352.33,
 324.72,
 445.3,
 426.94,
 400.45,
 245.34,
 218.48,
 366.76,
 264.25,
 294.88,
 225.8,
 176.97,
 78.75,
 204.25,
 241.4,
 185.64,
 190.01,
 114.08,
 161.53,
 95.1,
 176.14,
 405.92,
 52.53,
 132.97,
 92.18,
 92.88,
 133.52,
 97.74,
 56.54,
 87.21,
 41.98,
 460.32,
 328.92,
 197.99,
 168.46,
 288.1,
 174.53,
 269.87,
 194.41,
 233.61,
 327.16,
 117.1,
 0.0,
 598.11,
 847.4,
 733.08,
 572.12,
 388.33,
 586.88,
 333.53,
 520.48,
 429.25,
 307.25,
 436.83,
 308.78,
 436.36,
 283.42,
 325.88,
 374.33,
 333.36,
 210.39,
 301.5,
 276.84,
 229.19,
 268.72,
 228.48,
 225.73,
 280.15,
 255.97,
 206.47,
 198.44,
 222.49,
 225.24,
 312.75,
 262.89,
 267.11,
 198.66,
 213.51,
 296.71,
 178.48,
 206.0,
 133.14,
 183.85,
 87.02,
 170.06,
 120.19,
 226.3,
 141.69,
 163.95,
 123.73,
 89.36,
 63.29,
 176.84,
 72.84,
 149.59,
 122.93,
 131.62,
 126.71,
 123.76,
 154.21,
 83.19,
 198.64,
 163.52,
 135.59,
 37.16,
 68.18,
 66.89,
 33.38,
 108.48,
 86.41,
 26.05,
 41.83,
 141.66,
 50.18,
 7.88,
 1243.65,
 402.72,
 190.53,
 407.27,
 351.79,
 264.69,
 138.57,
 229.83,
 56.36,
 78.2,
 131.65,
 1.96,
 247.34,
 1283.18,
 311.07,
 91.9,
 46.22,
 1182.33,
 1089.87,
 681.34,
 845.94,
 1379.64,
 824.85,
 869.2,
 742.08,
 362.96,
 495.89,
 395.83,
 456.56,
 448.09,
 261.76,
 270.71,
 457.03,
 207.61,
 263.34,
 129.85,
 282.08,
 291.57,
 295.46,
 188.36,
 284.67,
 159.35,
 98.03,
 126.59,
 175.32,
 127.43,
 139.93,
 114.18,
 97.05,
 72.46,
 95.36,
 52.33,
 169.82,
 119.68,
 103.52,
 292.69,
 67.21,
 49.0,
 45.35,
 19.5,
 40.84,
 7.21,
 0.0,
 0.0,
 1568.02,
 420.29,
 338.73,
 223.11,
 482.64,
 142.32,
 68.72,
 726.99,
 150.85,
 99.15,
 119.32,
 244.59,
 290.34,
 134.65,
 75.86,
 51.81,
 86.36,
 359.42,
 411.41,
 577.45,
 1338.58,
 659.5,
 633.55,
 502.14,
 443.05,
 381.71,
 424.45,
 441.0,
 452.74,
 429.79,
 342.59,
 295.94,
 251.15,
 295.81,
 289.61,
 358.14,
 246.97,
 304.95,
 246.49,
 224.02,
 163.8,
 226.72,
 261.93,
 168.29,
 177.08,
 187.16,
 229.11,
 175.34,
 314.63,
 135.68,
 77.49,
 196.33,
 100.78,
 127.05,
 166.61,
 195.75,
 87.19,
 187.78,
 71.04,
 99.7,
 86.11,
 98.8,
 83.94,
 70.36,
 148.19,
 93.44,
 28.39,
 47.25,
 36.93,
 84.22,
 105.13,
 20.42,
 19.42,
 28.73,
 28.09,
 50.6,
 55.7,
 787.63,
 125.79,
 211.52,
 1038.39,
 284.56,
 319.43,
 166.97,
 128.2,
 113.57,
 111.3,
 49.21,
 88.63,
 80.09,
 519.97,
 175.64,
 203.69,
 27.04,
 37.85,
 320.76,
 286.63,
 294.2,
 746.21,
 575.55,
 420.53,
 594.03,
 516.62,
 713.1,
 810.89,
 680.26,
 265.89,
 402.15,
 385.85,
 251.58,
 357.82,
 325.75,
 197.64,
 404.24,
 359.54,
 198.27,
 215.12,
 392.31,
 211.95,
 228.22,
 251.22,
 107.21,
 217.24,
 277.15,
 160.41,
 241.5,
 258.56,
 202.08,
 74.1,
 66.99,
 340.46,
 370.23,
 60.03,
 155.16,
 111.56,
 51.46,
 96.56,
 90.07,
 58.85,
 87.42,
 64.06,
 114.73,
 26.49,
 62.54,
 33.5,
 15.41,
 41.03,
 188.49,
 0.79,
 158.81,
 98.75,
 209.74,
 1648.91,
 470.38,
 299.46,
 108.43,
 39.77,
 334.68,
 205.85,
 173.91,
 238.49,
 64.77,
 30.18,
 604.21,
 238.68,
 509.12,
 217.2,
 435.87,
 133.03,
 913.24,
 860.95,
 762.88,
 756.94,
 422.59,
 413.02,
 484.5,
 440.2,
 397.54,
 357.26,
 287.42,
 594.05,
 293.77,
 273.81,
 249.51,
 364.36,
 362.78,
 334.5,
 331.74,
 254.1,
 276.48,
 327.4,
 283.67,
 262.78,
 225.03,
 344.33,
 362.28,
 218.28,
 207.86,
 229.25,
 167.05,
 311.47,
 210.06,
 170.55,
 275.08,
 420.15,
 151.21,
 271.3,
 325.32,
 119.53,
 145.21,
 216.39,
 166.37,
 266.58,
 293.11,
 94.52,
 168.56,
 180.2,
 265.59,
 164.7,
 167.74,
 150.8,
 186.58,
 189.1,
 174.05,
 218.96,
 173.87,
 168.97,
 118.14,
 267.83,
 159.23,
 113.89,
 173.5,
 329.3,
 175.34,
 96.01,
 138.02,
 112.19,
 136.92,
 181.66,
 135.13,
 130.8,
 207.52,
 148.05,
 61.42,
 130.13,
 79.7,
 202.21,
 56.59,
 54.97,
 78.95,
 104.33,
 91.66,
 64.2,
 126.61,
 65.39,
 50.11,
 140.26,
 246.64,
 118.46,
 44.46,
 134.61,
 82.46,
 80.98,
 82.06,
 58.87,
 65.01,
 34.24,
 111.09,
 24.69,
 24.69,
 49.29,
 20.12,
 84.41,
 17.66,
 40.25,
 50.66,
 22.06,
 19.05,
 323.43,
 0.0,
 0.0,
 148.35,
 48.05,
 1381.08,
 943.67,
 273.97,
 325.37,
 150.17,
 86.84,
 173.6,
 161.5,
 102.47,
 71.29,
 174.02,
 138.76,
 54.53,
 722.17,
 514.56,
 101.02,
 268.43,
 261.78,
 183.1,
 67.24,
 108.94,
 379.21,
 349.39,
 353.58,
 84.49,
 641.96,
 1236.09,
 659.28,
 1627.25,
 666.88,
 600.77,
 558.75,
 631.09,
 545.82,
 497.84,
 693.45,
 401.18,
 317.21,
 229.86,
 628.95,
 350.73,
 675.18,
 513.27,
 276.85,
 297.89,
 ...]

In [112]:
budgets['roi'] = roi_list

In [113]:
budgets.head()

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross,roi
0,1,"Dec 18, 2009",Avatar,425000000,"$760,507,625",2776345279,653.26
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,410600000,"$241,063,875",1045663875,254.67
2,3,"Jun 7, 2019",Dark Phoenix,350000000,"$42,762,350",149762350,42.79
3,4,"May 1, 2015",Avengers: Age of Ultron,330600000,"$459,005,868",1403013963,424.38
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,317000000,"$620,181,382",1316721747,415.37

In [101]:
genre_ratings_df = pd.merge(basics,
                            ratings,
                            on = ['tconst'],
                           how = 'left')

In [102]:
genre_ratings_df.nlargest(100, 'numvotes').sort_values(by=['numvotes'], ascending = False)

,tconst,primary_title,original_title,start_year,runtime_minutes,genres,averagerating,numvotes
7066,tt1375666,Inception,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,1841066.0
6900,tt1345836,The Dark Knight Rises,The Dark Knight Rises,2012,164.0,"Action,Thriller",8.4,1387769.0
311,tt0816692,Interstellar,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.6,1299334.0
20342,tt1853728,Django Unchained,Django Unchained,2012,165.0,"Drama,Western",8.4,1211405.0
356,tt0848228,The Avengers,The Avengers,2012,143.0,"Action,Adventure,Sci-Fi",8.1,1183655.0
...,...,...,...,...,...,...,...,...
170,tt0470752,Ex Machina,Ex Machina,2014,108.0,"Drama,Mystery,Sci-Fi",7.7,424542.0
12366,tt1659337,The Perks of Being a Wallflower,The Perks of Being a Wallflower,2012,103.0,Drama,8.0,422671.0
18045,tt1800241,American Hustle,American Hustle,2013,138.0,"Crime,Drama",7.2,418221.0
48318,tt2872718,Nightcrawler,Nightcrawler,2014,117.0,"Crime,Drama,Thriller",7.9,404476.0
6395,tt1291584,Warrior,Warrior,2011,140.0,"Drama,Sport",8.2,403755.0

From the merged data set we can see popularity, based off number of votes and average rating along with the genres of the title.

In [103]:
genre_ratings_df.nlargest(100, 'numvotes').mean()

start_year           2013.250
runtime_minutes       127.990
averagerating           7.671
numvotes           606520.830
dtype: float64

In [104]:
genre_ratings_df.nlargest(100, 'numvotes').std()

start_year              2.212796
runtime_minutes        20.002270
averagerating           0.517823
numvotes           224778.932318
dtype: float64

In [105]:
genre_ratings_df['averagerating'].mean()

6.332728552859617

Here we can see the average run time among the top 100 most popular movies is 128 minutes, with a standard deviation of 20 minutes. The average rating is 7.67, which is 1.34 points higher than the average.

In [106]:
import matplotlib.ticker as mtick

budgets['']

KeyError: ''